import {test,expect} from '@playwright/test';
test('portfolio to KO decision, approval and verification',async({page})=>{
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'Turn exposure into action.'})).toBeVisible();
 await page.getByRole('button',{name:'Incident recorded'}).first().click();
 await expect(page.getByRole('dialog',{name:'Evidence and provenance'})).toBeVisible();
 await page.getByRole('button',{name:'Close'}).click();
 await page.screenshot({path:'docs/screenshots/portfolio.png',fullPage:true,caret:'initial'});
 await page.getByRole('link',{name:/Open workspace/}).first().click();
 await expect(page.getByRole('heading',{name:'Compressor causal health'})).toBeVisible();
 await page.getByRole('button',{name:'Open hourly tag metadata'}).click();
 await expect(page.getByRole('dialog',{name:'Evidence and provenance'})).toContainText('MM/S');
 await page.getByRole('button',{name:'Close'}).click();
 await page.screenshot({path:'docs/screenshots/ko.png',fullPage:true,caret:'initial'});
 await page.getByRole('button',{name:'Select'}).nth(3).click();
 await page.getByLabel('Decision rationale').fill('Weekly water and vibration evidence justify a planned intervention.');
 await page.getByRole('button',{name:'Validate operating state'}).click();
 await page.getByRole('button',{name:'Engineer assessment'}).click();
 await page.getByRole('button',{name:'Propose decision'}).click();
 await expect(page.getByText('Manager approval required.')).toBeVisible();
 await page.getByLabel('Acting role').selectOption('Maintenance / Reliability Manager');
 await page.getByRole('button',{name:'Record manager approval'}).click();
 await page.getByRole('button',{name:'Planner starts work'}).click();
 await page.getByLabel('Field execution evidence').fill('Cooler plug leak test WT-01 and bearing work pack WB-01');
 await page.getByRole('button',{name:'Technician completes work'}).click();
 await page.getByLabel('Post-action result / operation confirmation').fill('Restart at 55 t/h; water and displacement trending toward baseline');
 await page.getByRole('button',{name:'Supervisor confirms restoration'}).click();
 await expect(page.getByText('PERFORMANCE RESTORED',{exact:false}).first()).toBeVisible();
 await page.getByRole('button',{name:'Engineer starts monitoring'}).click();
 await page.getByRole('button',{name:'Verify technical closure'}).click();
 await expect(page.getByText('Technician cannot verify.')).toBeVisible();
 await page.locator('.checklist input[type=checkbox]').first().check();
 await page.locator('.checklist input[type=checkbox]').nth(1).check();
 await page.locator('.checklist input[type=checkbox]').nth(2).check();
 await page.getByLabel('Verifier role').selectOption('Reliability Engineer');
 await page.getByRole('button',{name:'Verify technical closure'}).click();
 await expect(page.getByText('Verified closed',{exact:true})).toBeVisible();
 await page.goto('/actions');
 await expect(page.getByText('VERIFIED CLOSED',{exact:true})).toBeVisible();
});
test('HE rate-change does not propose cleaning',async({page})=>{
 await page.goto('/assets/he-3301');
 await expect(page.getByRole('heading',{name:'Fouling & cleaning decision'})).toBeVisible();
 await page.screenshot({path:'docs/screenshots/he.png',fullPage:true,caret:'initial'});
 await page.getByLabel('Demo scenario').selectOption('rate-change');
 await expect(page.getByText('Do not recommend cleaning from raw duty change alone.',{exact:false}).first()).toBeVisible();
 await page.getByRole('button',{name:'Rate-normalized demonstration'}).click();
 await expect(page.getByText('0.355',{exact:false}).first()).toBeVisible();
 await page.screenshot({path:'docs/screenshots/he-rate-change.png',fullPage:true,caret:'initial'});
});

test('HE fouling follows approval and effectiveness gate',async({page})=>{
 await page.goto('/assets/he-3301');
 await page.getByRole('button',{name:'Select'}).nth(3).click();
 await page.getByLabel('Decision rationale').fill('Normalized dP and duty deteriorate with heavy-ends; plan cleaning.');
 await page.getByRole('button',{name:'Validate operating state'}).click();
 await page.getByRole('button',{name:'Engineer assessment'}).click();
 await page.getByRole('button',{name:'Propose decision'}).click();
 await page.getByLabel('Acting role').selectOption('Operations Manager');
 await page.getByRole('button',{name:'Record manager approval'}).click();
 await page.getByRole('button',{name:'Planner starts work'}).click();
 await page.getByLabel('Field execution evidence').fill('Hydro-jet cleaning and deposit inspection record HE-01');
 await page.getByRole('button',{name:'Technician completes work'}).click();
 await page.getByLabel('Post-action result / operation confirmation').fill('Tube dP 0.337 bar and duty 98.4%; rate restored');
 await page.getByRole('button',{name:'Supervisor confirms restoration'}).click();
 await page.getByRole('button',{name:'Engineer starts monitoring'}).click();
 await page.locator('.checklist input[type=checkbox]').first().check();
 await page.locator('.checklist input[type=checkbox]').nth(1).check();
 await page.getByLabel('Verifier role').selectOption('Process Engineer');
 await page.getByRole('button',{name:'Verify technical closure'}).click();
 await expect(page.getByText('Prerequisites missing for verify.')).toBeVisible();
 await page.locator('.checklist input[type=checkbox]').nth(2).check();
 await page.getByRole('button',{name:'Verify technical closure'}).click();
 await expect(page.getByText('Verified closed',{exact:true})).toBeVisible();
});
test('KO missing water uses simulated provenance and blocks causal proposal',async({page})=>{
 await page.goto('/assets/ko-3201');
 await page.getByLabel('Demo scenario').selectOption('insufficient');
 const water=page.locator('.condition .card').nth(1);
 await expect(water).toContainText('Missing');
 await expect(water).toContainText('Simulated · Demo scenario');
 await water.getByRole('button',{name:'Simulated · Demo scenario'}).click();
 await expect(page.getByRole('dialog',{name:'Evidence and provenance'})).toContainText('KO evidence-insufficient scenario');
 await page.getByRole('button',{name:'Close'}).click();
 await expect(page.getByRole('button',{name:'Record insufficient evidence'})).toBeVisible();
});
