'use client';

import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';

type Tone='focus'|'context';
const palette={navy:0x152b3b,steel:0x758892,steelDark:0x40525d,steelLight:0xb3c1c6,blue:0x1686b9,blueDark:0x084b78,yellow:0xe6d954,pipe:0x527582};

function material(color:number,roughness=.3){return new THREE.MeshPhysicalMaterial({color,metalness:.7,roughness,clearcoat:.35});}
function mesh(group:THREE.Group,geometry:THREE.BufferGeometry,color:number,pos:[number,number,number],rot:[number,number,number]=[0,0,0]){const item=new THREE.Mesh(geometry,material(color));item.position.set(...pos);item.rotation.set(...rot);item.castShadow=true;item.receiveShadow=true;group.add(item);return item;}
function cylinder(group:THREE.Group,r:number,l:number,color:number,pos:[number,number,number],rot:[number,number,number]=[0,0,Math.PI/2]){return mesh(group,new THREE.CylinderGeometry(r,r,l,32),color,pos,rot);}
function tube(group:THREE.Group,points:[number,number,number][],radius=.15,color=palette.pipe){const curve=new THREE.CatmullRomCurve3(points.map(point=>new THREE.Vector3(...point)));return mesh(group,new THREE.TubeGeometry(curve,48,radius,10,false),color,[0,0,0]);}
function colors(tone:Tone){return tone==='focus'?{body:palette.blue,side:palette.blueDark,accent:palette.yellow}:{body:palette.steel,side:palette.steelDark,accent:palette.steelLight};}
function base(group:THREE.Group,x:number,width=3.1){mesh(group,new THREE.BoxGeometry(width,.22,2.2),palette.navy,[x,-1.18,0]);for(const dx of [-width*.36,width*.36])for(const z of [-.75,.75])mesh(group,new THREE.BoxGeometry(.25,.45,.25),palette.steelDark,[x+dx,-1.5,z]);}
function pump(group:THREE.Group,x:number,tone:Tone){const c=colors(tone);base(group,x);cylinder(group,.86,.58,c.side,[x-.9,-.32,0],[0,Math.PI/2,0]);mesh(group,new THREE.SphereGeometry(.86,28,18),c.body,[x-.58,-.32,0]);cylinder(group,.28,.95,c.accent,[x+.34,-.32,0]);cylinder(group,.56,1.55,c.body,[x+1.5,-.32,0]);for(const dx of [1.05,1.45,1.92])mesh(group,new THREE.TorusGeometry(.57,.028,8,32),c.accent,[x+dx,-.32,0],[0,Math.PI/2,0]);tube(group,[[x-.58,.34,0],[x-.58,.96,0],[x-.1,.96,0]],.15,c.accent);}
function compressor(group:THREE.Group,x:number,tone:Tone){const c=colors(tone);base(group,x,3.6);cylinder(group,.7,1.15,c.side,[x-1.2,-.24,0]);cylinder(group,.96,2.5,c.body,[x+.18,-.24,0]);for(const dx of [-.8,-.05,.73])mesh(group,new THREE.TorusGeometry(.97,.04,8,36),c.accent,[x+dx,-.24,0],[0,Math.PI/2,0]);cylinder(group,.58,.85,c.body,[x+1.74,-.24,0]);mesh(group,new THREE.BoxGeometry(.38,.72,.9),c.side,[x+2.23,-.24,0]);tube(group,[[x-1.1,.28,.76],[x-1.1,.98,.76],[x-.48,1.12,.76]],.09,c.accent);tube(group,[[x+1.42,-.66,.76],[x+1.84,-.66,.76],[x+1.84,.24,.76]],.08,c.accent);}
function exchanger(group:THREE.Group,x:number,tone:Tone){const c=colors(tone);base(group,x,4.4);cylinder(group,1.02,3.8,c.body,[x,-.18,0]);for(const dx of [-1.9,1.9]){cylinder(group,1.08,.28,c.side,[x+dx,-.18,0]);mesh(group,new THREE.TorusGeometry(1.07,.05,8,36),c.accent,[x+dx+(dx<0?-.15:.15),-.18,0],[0,Math.PI/2,0]);}for(const dx of [-1.25,-.62,0,.62,1.25])mesh(group,new THREE.TorusGeometry(1.03,.025,8,32),c.accent,[x+dx,-.18,0],[0,Math.PI/2,0]);tube(group,[[x-1.2,.76,0],[x-1.2,1.45,0],[x-.55,1.45,0]],.18,c.accent);tube(group,[[x+1.25,-1.02,0],[x+1.25,-1.32,.9],[x+1.85,-1.32,.9]],.15,c.accent);}
function blower(group:THREE.Group,x:number,tone:Tone){const c=colors(tone);base(group,x);mesh(group,new THREE.SphereGeometry(.9,28,18),c.body,[x-.7,-.28,0]);cylinder(group,.62,.56,c.side,[x-1.22,-.28,0]);for(let i=0;i<5;i++){const blade=mesh(group,new THREE.BoxGeometry(.12,.62,.2),c.accent,[x-.7,-.28,.02]);blade.rotation.set(0,0,i*Math.PI/2.5);blade.position.x=x-.7+Math.cos(i*Math.PI/2.5)*.3;blade.position.y=-.28+Math.sin(i*Math.PI/2.5)*.3;}cylinder(group,.26,.98,c.accent,[x+.25,-.28,0]);cylinder(group,.55,1.55,c.body,[x+1.42,-.28,0]);tube(group,[[x-.72,.3,0],[x-.72,.95,0],[x-.15,.95,0]],.15,c.accent);}
function buildPlant(){const plant=new THREE.Group();
 const floor=new THREE.Mesh(new THREE.BoxGeometry(24,.28,7.5),material(0x173542,.44));floor.position.y=-1.85;floor.receiveShadow=true;plant.add(floor);
 for(const z of [-2.7,0,2.7]){const rail=new THREE.Mesh(new THREE.BoxGeometry(22,.05,.06),material(0x5e8996));rail.position.set(0,-1.68,z);plant.add(rail);}
 pump(plant,-8,'context'); compressor(plant,-4,'focus'); pump(plant,0,'context'); exchanger(plant,4,'focus'); blower(plant,8,'context');
 tube(plant,[[-5.6,-.32,0],[-5.2,-.32,0],[-5.2,.45,0],[-2.65,.45,0]],.2,palette.pipe);
 tube(plant,[[-1.68,-.32,0],[-1.25,-.32,0],[-1.25,.45,0],[-.78,.45,0]],.2,palette.pipe);
 tube(plant,[[1.7,-.32,0],[2.1,-.32,0],[2.1,.45,0],[2.08,.45,0]],.2,palette.pipe);
 tube(plant,[[5.92,-.18,0],[6.28,-.18,0],[6.28,.42,0],[6.58,.42,0]],.2,palette.pipe);
 return plant;}

export function EquipmentFleet(){
 const mount=useRef<HTMLDivElement>(null);const [failed,setFailed]=useState(false);
 useEffect(()=>{const host=mount.current;if(!host)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch{setFailed(true);return;}renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.domElement.className='plant-canvas';renderer.domElement.setAttribute('aria-hidden','true');host.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color(0x0d2531);const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(13,9,20);camera.lookAt(0,-.35,0);const plant=buildPlant();plant.rotation.y=-.42;scene.add(plant);scene.add(new THREE.HemisphereLight(0xdff8ff,0x102c38,2.6));const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(-8,15,12);key.castShadow=true;scene.add(key);const cyan=new THREE.DirectionalLight(0x58c9e5,2.1);cyan.position.set(9,5,-12);scene.add(cyan);const warm=new THREE.PointLight(0xe6d954,18,12,2);warm.position.set(0,4,4);scene.add(warm);
 let width=0,height=0,dragging=false,lastX=0,lastY=0;const draw=()=>{const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;if(w!==width||h!==height){width=w;height=h;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}renderer.render(scene,camera);};const resize=new ResizeObserver(draw);resize.observe(host);draw();
 const down=(event:PointerEvent)=>{if(event.button!==0)return;dragging=true;lastX=event.clientX;lastY=event.clientY;renderer.domElement.setPointerCapture(event.pointerId);};const move=(event:PointerEvent)=>{if(!dragging)return;const dx=event.clientX-lastX,dy=event.clientY-lastY;lastX=event.clientX;lastY=event.clientY;plant.rotation.y+=dx*.012;plant.rotation.x=Math.max(-1.15,Math.min(1.15,plant.rotation.x+dy*.009));draw();};const up=()=>{dragging=false;};const wheel=(event:WheelEvent)=>{event.preventDefault();camera.position.multiplyScalar(event.deltaY>0?1.08:.92);camera.position.clampLength(13,32);camera.lookAt(0,-.35,0);draw();};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);renderer.domElement.addEventListener('wheel',wheel,{passive:false});
 return()=>{resize.disconnect();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointercancel',up);renderer.domElement.removeEventListener('wheel',wheel);host.replaceChildren();plant.traverse(object=>{if(object instanceof THREE.Mesh){object.geometry.dispose();const materials=Array.isArray(object.material)?object.material:[object.material];materials.forEach(item=>item.dispose());}});renderer.dispose();};},[]);
 return <section className="equipment-fleet" aria-labelledby="fleet-title"><div className="fleet-heading"><div><div className="eyebrow">Connected equipment landscape</div><h2 id="fleet-title">Five assets, two active investigations</h2><p>Rotate the 3D plant to inspect the connected equipment. Red alerts identify the two assets in the decision queue.</p></div></div><div className="plant-map-layout"><div className="plant-scene-wrap"><div className="plant-webgl" role="group" aria-label="Interactive 3D plant with five connected equipment assets" ref={mount}/><span className="plant-alert alert-ko" title="KO-3201 requires reliability review" aria-label="KO-3201 priority alert">!</span><span className="plant-alert alert-he" title="HE-3301 requires process review" aria-label="HE-3301 priority alert">!</span>{failed&&<div className="plant-fallback">The interactive 3D view is unavailable in this browser.</div>}</div><aside className="plant-focus-card" aria-label="Current investigation focus"><div className="eyebrow">Decision focus</div><h3>Investigate these first</h3><div className="plant-focus-row ko"><span>!</span><div><strong>KO-3201</strong><small>Compressor bearing risk</small></div></div><div className="plant-focus-row he"><span>!</span><div><strong>HE-3301</strong><small>Exchanger fouling risk</small></div></div><p>Grey equipment remains visible as connected operating context.</p><div className="plant-gesture">Drag to rotate<br/>Scroll to zoom</div></aside></div></section>;
}
